-- ============================================================================
-- FraudShield 360 - Seed State Machine Transitions & Config
-- ============================================================================

USE DATABASE FRAUDSHIELD_360_DB;
USE SCHEMA AGENTS;

-- State machine transitions
INSERT INTO CASE_STATUS_TRANSITIONS (FROM_STATUS, TO_STATUS, LABEL, REQUIRED_ROLE, REQUIRES_FOUR_EYES)
VALUES
('OPEN', 'UNDER_REVIEW', 'Start Review', 'FRAUD_ANALYST_ROLE', FALSE),
('OPEN', 'RESOLVED_APPROVED', 'Approve & Release', 'FRAUD_ANALYST_ROLE', FALSE),
('OPEN', 'ESCALATED', 'Escalate', 'FRAUD_ANALYST_ROLE', FALSE),
('UNDER_REVIEW', 'RESOLVED_APPROVED', 'Approve & Release', 'FRAUD_ANALYST_ROLE', FALSE),
('UNDER_REVIEW', 'ESCALATED', 'Escalate', 'FRAUD_ANALYST_ROLE', FALSE),
('ESCALATED', 'UNDER_REVIEW', 'Return to Analyst', 'COMPLIANCE_OFFICER_ROLE', FALSE),
('ESCALATED', 'RESOLVED_APPROVED', 'Approve & Release', 'COMPLIANCE_OFFICER_ROLE', TRUE),
('ESCALATED', 'PENDING_SAR', 'Block & File SAR', 'COMPLIANCE_OFFICER_ROLE', TRUE),
('PENDING_SAR', 'SAR_FILED', 'File SAR', 'COMPLIANCE_OFFICER_ROLE', TRUE),
('PENDING_SAR', 'CLOSED', 'Close Case', 'COMPLIANCE_OFFICER_ROLE', FALSE),
('RESOLVED_APPROVED', 'CLOSED', 'Close Case', 'COMPLIANCE_OFFICER_ROLE', FALSE);

-- App config thresholds
INSERT INTO APP_CONFIG (CONFIG_KEY, CONFIG_VALUE) VALUES
('ANALYST_MAX_RISK_SCORE', '60'),
('ANALYST_BLOCKED_TIERS', 'CRITICAL,HIGH');

-- Default admin user mapping (update USER_NAME to your Snowflake username)
INSERT INTO USER_ROLE_MAPPING (USER_NAME, ASSIGNED_ROLE, ASSIGNED_BY, STATUS)
VALUES (CURRENT_USER(), 'FRAUDSHIELD_ACCESS_ADMIN_ROLE', 'SYSTEM_ADMIN', 'ACTIVE');
