-- ============================================================================
-- FraudShield 360 - Database & Schema Setup
-- Run as: ACCOUNTADMIN
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- Database
CREATE DATABASE IF NOT EXISTS FRAUDSHIELD_360_DB;

-- Schemas
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.RAW;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.DOCUMENTS;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.AGENTS;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.ANALYTICS;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'X-Small'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;
