-- ============================================================================
-- FraudShield 360 - RAW Schema Tables
-- ============================================================================

USE DATABASE FRAUDSHIELD_360_DB;
USE SCHEMA RAW;

-- RAW_ACCOUNTS
CREATE TABLE IF NOT EXISTS RAW_ACCOUNTS (
    ACCOUNT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    CUSTOMER_NAME_HASH VARCHAR(256),
    KYC_STATUS VARCHAR(20),
    RISK_TIER VARCHAR(10),
    ONBOARDING_DATE DATE,
    ACCOUNT_TYPE VARCHAR(50),
    DOMICILE_COUNTRY VARCHAR(64),
    REGISTERED_EMAIL_HASH VARCHAR(256),
    REGISTERED_MOBILE_HASH VARCHAR(256),
    CUSTOMER_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    EMAIL_ADDRESS VARCHAR(100)
);

-- RAW_TRANSACTIONS
CREATE TABLE IF NOT EXISTS RAW_TRANSACTIONS (
    TXN_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_ID VARCHAR(20),
    AMOUNT NUMBER(18,2),
    MERCHANT VARCHAR(255),
    GEO_COUNTRY VARCHAR(64),
    GEO_CITY VARCHAR(128),
    CHANNEL VARCHAR(32),
    TXN_TIMESTAMP TIMESTAMP_TZ,
    DEVICE_ID VARCHAR(128)
);

-- RAW_WATCHLIST
CREATE TABLE IF NOT EXISTS RAW_WATCHLIST (
    ENTITY_NAME VARCHAR(255),
    ENTITY_TYPE VARCHAR(50),
    LIST_SOURCE VARCHAR(50),
    JURISDICTION VARCHAR(64),
    DATE_ADDED DATE,
    CONFIDENCE_SCORE NUMBER(3,2)
);

-- RAW_VERIFICATION_RESPONSES
CREATE TABLE IF NOT EXISTS RAW_VERIFICATION_RESPONSES (
    VERIFICATION_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    TXN_ID VARCHAR(36),
    RESPONSE_TYPE VARCHAR(30),
    RESPONSE_TIME_MINUTES NUMBER(5,1)
);
