-- ============================================================================
-- FraudShield 360 - AGENTS Schema Tables
-- ============================================================================

USE DATABASE FRAUDSHIELD_360_DB;
USE SCHEMA AGENTS;

-- FRAUD_ALERTS
CREATE TABLE IF NOT EXISTS FRAUD_ALERTS (
    CASE_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_ID VARCHAR(20),
    TXN_ID VARCHAR(36),
    ALERT_TIMESTAMP TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    ALERT_TYPE VARCHAR(50),
    RISK_SCORE INTEGER,
    RISK_TIER VARCHAR(10),
    TRIGGERED_SIGNALS ARRAY,
    ASSIGNED_ANALYST VARCHAR(100),
    CASE_STATUS VARCHAR(20) DEFAULT 'OPEN',
    RESOLUTION_NOTES TEXT,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_BY VARCHAR(100),
    RESOLVED_AT TIMESTAMP_TZ,
    ESCALATED_BY VARCHAR(100),
    ESCALATED_AT TIMESTAMP_TZ,
    ESCALATED_TO VARCHAR(50),
    SLA_DUE_AT TIMESTAMP_TZ,
    ROW_VERSION INTEGER DEFAULT 1
);

-- CUSTOMER_VERIFICATION_EVENTS
CREATE TABLE IF NOT EXISTS CUSTOMER_VERIFICATION_EVENTS (
    EVENT_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    CASE_ID VARCHAR(36),
    ACCOUNT_ID VARCHAR(20),
    TXN_ID VARCHAR(36),
    VERIFICATION_METHOD VARCHAR(30),
    RESPONSE_TYPE VARCHAR(30),
    RESPONSE_TIMESTAMP TIMESTAMP_TZ,
    RESPONSE_TIME_MINUTES NUMBER(5,1),
    DEVICE_FINGERPRINT VARCHAR(256),
    IP_ADDRESS VARCHAR(45),
    NOTES TEXT,
    ALERT_DISPATCHED_AT TIMESTAMP_TZ,
    EMAIL_STATUS VARCHAR(20),
    PUSH_STATUS VARCHAR(20),
    TOKEN_VALID BOOLEAN,
    TOKEN_HASH VARCHAR(64),
    EXPLANATION_CUSTOMER TEXT
);

-- USER_ROLE_MAPPING
CREATE TABLE IF NOT EXISTS USER_ROLE_MAPPING (
    MAPPING_ID VARCHAR DEFAULT UUID_STRING(),
    USER_NAME VARCHAR(100),
    ASSIGNED_ROLE VARCHAR(50),
    ASSIGNED_BY VARCHAR(100),
    ASSIGNED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT TIMESTAMP_TZ,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    APPROVED_BY VARCHAR(100)
);

-- AGENT_AUDIT_LOG
CREATE TABLE IF NOT EXISTS AGENT_AUDIT_LOG (
    EVENT_ID VARCHAR DEFAULT UUID_STRING(),
    CASE_ID VARCHAR,
    ACTION_TAKEN VARCHAR,
    RESOLVED_BY VARCHAR,
    RESOLVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEWER_NOTES TEXT
);

-- ACCOUNT_RISK_FLAGS
CREATE TABLE IF NOT EXISTS ACCOUNT_RISK_FLAGS (
    FLAG_ID VARCHAR DEFAULT UUID_STRING(),
    ACCOUNT_ID VARCHAR,
    FLAG_TYPE VARCHAR,
    TRIGGERED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT TIMESTAMP_TZ
);

-- CASE_STATUS_TRANSITIONS (state machine edges)
CREATE TABLE IF NOT EXISTS CASE_STATUS_TRANSITIONS (
    FROM_STATUS VARCHAR(30),
    TO_STATUS VARCHAR(30),
    LABEL VARCHAR(50),
    REQUIRED_ROLE VARCHAR(50),
    REQUIRES_FOUR_EYES BOOLEAN DEFAULT FALSE
);

-- CASE_WORKFLOW_QUEUE
CREATE TABLE IF NOT EXISTS CASE_WORKFLOW_QUEUE (
    QUEUE_ID VARCHAR DEFAULT UUID_STRING(),
    CASE_ID VARCHAR(36),
    ASSIGNED_TO_ROLE VARCHAR(50),
    QUEUED_BY VARCHAR(100),
    QUEUED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    SLA_DUE_AT TIMESTAMP_TZ,
    STATUS VARCHAR(20) DEFAULT 'PENDING'
);

-- SAR_FILINGS
CREATE TABLE IF NOT EXISTS SAR_FILINGS (
    FILING_ID VARCHAR DEFAULT UUID_STRING(),
    CASE_ID VARCHAR(36),
    OPENED_BY VARCHAR(100),
    OPENED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    FILING_DEADLINE TIMESTAMP_TZ,
    FILED_BY VARCHAR(100),
    FILED_AT TIMESTAMP_TZ,
    STATUS VARCHAR(20) DEFAULT 'PENDING'
);

-- APP_CONFIG
CREATE TABLE IF NOT EXISTS APP_CONFIG (
    CONFIG_KEY VARCHAR(100) PRIMARY KEY,
    CONFIG_VALUE VARCHAR(500)
);

-- ACCESS_REQUESTS
CREATE TABLE IF NOT EXISTS ACCESS_REQUESTS (
    REQUEST_ID VARCHAR DEFAULT UUID_STRING(),
    TARGET_USER VARCHAR(100),
    REQUESTED_ROLE VARCHAR(50),
    REQUESTED_BY VARCHAR(100),
    REQUESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    APPROVED_BY VARCHAR(100),
    APPROVED_AT TIMESTAMP_TZ,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    NOTES TEXT
);

-- AGENT_AUDIT_LOG_V (view)
CREATE OR REPLACE VIEW AGENT_AUDIT_LOG_V AS
SELECT
    EVENT_ID,
    CASE_ID,
    ACTION_TAKEN,
    RESOLVED_BY AS ACTOR,
    RESOLVED_AT AS EVENT_TIMESTAMP,
    REVIEWER_NOTES AS DETAILS
FROM AGENT_AUDIT_LOG
ORDER BY RESOLVED_AT DESC;
