-- ============================================================================
-- FraudShield 360 — Complete Setup Script
-- Run as ACCOUNTADMIN in a Snowflake worksheet
-- ============================================================================

-- ============================================================================
-- 1. DATABASE, SCHEMAS, WAREHOUSE
-- ============================================================================
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS FRAUDSHIELD_360_DB;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.RAW;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.DOCUMENTS;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.AGENTS;
CREATE SCHEMA IF NOT EXISTS FRAUDSHIELD_360_DB.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'X-Small'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

USE DATABASE FRAUDSHIELD_360_DB;

-- ============================================================================
-- 2. ROLES
-- ============================================================================
CREATE ROLE IF NOT EXISTS FRAUD_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS COMPLIANCE_OFFICER_ROLE;
CREATE ROLE IF NOT EXISTS AUDIT_ROLE;
CREATE ROLE IF NOT EXISTS FRAUDSHIELD_ACCESS_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS COCO_AUTOMATION_ROLE;

GRANT USAGE ON DATABASE FRAUDSHIELD_360_DB TO ROLE FRAUD_ANALYST_ROLE;
GRANT USAGE ON DATABASE FRAUDSHIELD_360_DB TO ROLE COMPLIANCE_OFFICER_ROLE;
GRANT USAGE ON DATABASE FRAUDSHIELD_360_DB TO ROLE AUDIT_ROLE;

GRANT USAGE ON SCHEMA AGENTS TO ROLE FRAUD_ANALYST_ROLE;
GRANT USAGE ON SCHEMA AGENTS TO ROLE COMPLIANCE_OFFICER_ROLE;
GRANT USAGE ON SCHEMA AGENTS TO ROLE AUDIT_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE FRAUD_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COMPLIANCE_OFFICER_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AUDIT_ROLE;

-- ============================================================================
-- 3. RAW SCHEMA TABLES
-- ============================================================================
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_ACCOUNTS (
    ACCOUNT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    CUSTOMER_NAME_HASH VARCHAR(256),
    KYC_STATUS VARCHAR(20),
    RISK_TIER VARCHAR(10),
    ONBOARDING_DATE DATE,
    ACCOUNT_TYPE VARCHAR(50),
    DOMICILE_COUNTRY VARCHAR(64),
    REGISTERED_EMAIL_HASH VARCHAR(256),
    REGISTERED_MOBILE_HASH VARCHAR(256),
    CUSTOMER_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    EMAIL_ADDRESS VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS RAW_TRANSACTIONS (
    TXN_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_ID VARCHAR(20),
    AMOUNT NUMBER(18,2),
    MERCHANT VARCHAR(255),
    GEO_COUNTRY VARCHAR(64),
    GEO_CITY VARCHAR(128),
    CHANNEL VARCHAR(32),
    TXN_TIMESTAMP TIMESTAMP_TZ,
    DEVICE_ID VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS RAW_WATCHLIST (
    ENTITY_NAME VARCHAR(255),
    ENTITY_TYPE VARCHAR(50),
    LIST_SOURCE VARCHAR(50),
    JURISDICTION VARCHAR(64),
    DATE_ADDED DATE,
    CONFIDENCE_SCORE NUMBER(3,2)
);

CREATE TABLE IF NOT EXISTS RAW_VERIFICATION_RESPONSES (
    VERIFICATION_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    TXN_ID VARCHAR(36),
    RESPONSE_TYPE VARCHAR(30),
    RESPONSE_TIME_MINUTES NUMBER(5,1)
);

-- ============================================================================
-- 4. AGENTS SCHEMA TABLES
-- ============================================================================
USE SCHEMA AGENTS;

CREATE TABLE IF NOT EXISTS FRAUD_ALERTS (
    CASE_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_ID VARCHAR(20),
    TXN_ID VARCHAR(36),
    ALERT_TIMESTAMP TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    ALERT_TYPE VARCHAR(50),
    RISK_SCORE INTEGER,
    RISK_TIER VARCHAR(10),
    TRIGGERED_SIGNALS ARRAY,
    ASSIGNED_ANALYST VARCHAR(100),
    CASE_STATUS VARCHAR(20) DEFAULT 'OPEN',
    RESOLUTION_NOTES TEXT,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_BY VARCHAR(100),
    RESOLVED_AT TIMESTAMP_TZ,
    ESCALATED_BY VARCHAR(100),
    ESCALATED_AT TIMESTAMP_TZ,
    ESCALATED_TO VARCHAR(50),
    SLA_DUE_AT TIMESTAMP_TZ,
    ROW_VERSION INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS CUSTOMER_VERIFICATION_EVENTS (
    EVENT_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    CASE_ID VARCHAR(36),
    ACCOUNT_ID VARCHAR(20),
    TXN_ID VARCHAR(36),
    VERIFICATION_METHOD VARCHAR(30),
    RESPONSE_TYPE VARCHAR(30),
    RESPONSE_TIMESTAMP TIMESTAMP_TZ,
    RESPONSE_TIME_MINUTES NUMBER(5,1),
    DEVICE_FINGERPRINT VARCHAR(256),
    IP_ADDRESS VARCHAR(45),
    NOTES TEXT,
    ALERT_DISPATCHED_AT TIMESTAMP_TZ,
    EMAIL_STATUS VARCHAR(20),
    PUSH_STATUS VARCHAR(20),
    TOKEN_VALID BOOLEAN,
    TOKEN_HASH VARCHAR(64),
    EXPLANATION_CUSTOMER TEXT
);

CREATE TABLE IF NOT EXISTS USER_ROLE_MAPPING (
    MAPPING_ID VARCHAR DEFAULT UUID_STRING(),
    USER_NAME VARCHAR(100),
    ASSIGNED_ROLE VARCHAR(50),
    ASSIGNED_BY VARCHAR(100),
    ASSIGNED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT TIMESTAMP_TZ,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    APPROVED_BY VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS AGENT_AUDIT_LOG (
    EVENT_ID VARCHAR DEFAULT UUID_STRING(),
    CASE_ID VARCHAR,
    ACTION_TAKEN VARCHAR,
    RESOLVED_BY VARCHAR,
    RESOLVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEWER_NOTES TEXT
);

CREATE TABLE IF NOT EXISTS ACCOUNT_RISK_FLAGS (
    FLAG_ID VARCHAR DEFAULT UUID_STRING(),
    ACCOUNT_ID VARCHAR,
    FLAG_TYPE VARCHAR,
    TRIGGERED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS CASE_STATUS_TRANSITIONS (
    FROM_STATUS VARCHAR(30),
    TO_STATUS VARCHAR(30),
    LABEL VARCHAR(50),
    REQUIRED_ROLE VARCHAR(50),
    REQUIRES_FOUR_EYES BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS CASE_WORKFLOW_QUEUE (
    QUEUE_ID VARCHAR DEFAULT UUID_STRING(),
    CASE_ID VARCHAR(36),
    ASSIGNED_TO_ROLE VARCHAR(50),
    QUEUED_BY VARCHAR(100),
    QUEUED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    SLA_DUE_AT TIMESTAMP_TZ,
    STATUS VARCHAR(20) DEFAULT 'PENDING'
);

CREATE TABLE IF NOT EXISTS SAR_FILINGS (
    FILING_ID VARCHAR DEFAULT UUID_STRING(),
    CASE_ID VARCHAR(36),
    OPENED_BY VARCHAR(100),
    OPENED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    FILING_DEADLINE TIMESTAMP_TZ,
    FILED_BY VARCHAR(100),
    FILED_AT TIMESTAMP_TZ,
    STATUS VARCHAR(20) DEFAULT 'PENDING'
);

CREATE TABLE IF NOT EXISTS APP_CONFIG (
    CONFIG_KEY VARCHAR(100) PRIMARY KEY,
    CONFIG_VALUE VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS ACCESS_REQUESTS (
    REQUEST_ID VARCHAR DEFAULT UUID_STRING(),
    TARGET_USER VARCHAR(100),
    REQUESTED_ROLE VARCHAR(50),
    REQUESTED_BY VARCHAR(100),
    REQUESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    APPROVED_BY VARCHAR(100),
    APPROVED_AT TIMESTAMP_TZ,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    NOTES TEXT
);

-- Audit view
CREATE OR REPLACE VIEW AGENT_AUDIT_LOG_V AS
SELECT EVENT_ID, CASE_ID, ACTION_TAKEN,
       RESOLVED_BY AS ACTOR, RESOLVED_AT AS EVENT_TIMESTAMP,
       REVIEWER_NOTES AS DETAILS
FROM AGENT_AUDIT_LOG
ORDER BY RESOLVED_AT DESC;

-- ============================================================================
-- 5. DOCUMENTS SCHEMA (RAG Infrastructure)
-- ============================================================================
USE SCHEMA DOCUMENTS;

CREATE STAGE IF NOT EXISTS REGULATORY_DOCS
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Internal stage for regulatory PDF documents';

CREATE TABLE IF NOT EXISTS DOCUMENT_CHUNKS (
    CHUNK_ID VARCHAR NOT NULL PRIMARY KEY,
    SOURCE_DOCUMENT VARCHAR,
    CHUNK_TEXT VARCHAR,
    PAGE_NUMBER INT
);

CREATE OR REPLACE CORTEX SEARCH SERVICE REGULATORY_SEARCH_SVC
  ON chunk_text
  ATTRIBUTES source_document, page_number
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
AS (
  SELECT chunk_id, source_document, chunk_text, page_number
  FROM DOCUMENT_CHUNKS
);

-- ============================================================================
-- 6. CURATED SCHEMA — Dynamic Table
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE CURATED.TRANSACTION_ENRICHED
  TARGET_LAG = '5 minutes'
  WAREHOUSE = COMPUTE_WH
AS
WITH base AS (
    SELECT t.*,
        CASE WHEN COUNT(*) OVER (PARTITION BY t.ACCOUNT_ID ORDER BY t.TXN_TIMESTAMP
            RANGE BETWEEN INTERVAL '1 HOUR' PRECEDING AND CURRENT ROW) > 3
            THEN TRUE ELSE FALSE END AS signal_velocity,
        CASE WHEN t.AMOUNT > 5 * MEDIAN(t.AMOUNT) OVER (PARTITION BY t.ACCOUNT_ID)
            THEN TRUE ELSE FALSE END AS signal_amount_anomaly,
        CASE WHEN t.GEO_COUNTRY != COALESCE(a.DOMICILE_COUNTRY, t.GEO_COUNTRY)
            THEN TRUE ELSE FALSE END AS signal_geo_mismatch,
        CASE WHEN w.ENTITY_NAME IS NOT NULL THEN TRUE ELSE FALSE END AS signal_watchlist_match,
        CASE WHEN MOD(t.AMOUNT, 1000) = 0 AND t.AMOUNT >= 1000 THEN TRUE ELSE FALSE END AS signal_round_number,
        CASE WHEN t.AMOUNT BETWEEN 9000 AND 9999 THEN TRUE ELSE FALSE END AS signal_structuring
    FROM RAW.RAW_TRANSACTIONS t
    LEFT JOIN RAW.RAW_ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
    LEFT JOIN (SELECT DISTINCT ENTITY_NAME FROM RAW.RAW_WATCHLIST) w
        ON CONTAINS(UPPER(t.MERCHANT), UPPER(SPLIT_PART(w.ENTITY_NAME, ' ', 1)))
        AND LENGTH(SPLIT_PART(w.ENTITY_NAME, ' ', 1)) > 3
),
scored AS (
    SELECT *, LEAST(100,
        (signal_velocity::INT*15) + (signal_amount_anomaly::INT*25) + (signal_geo_mismatch::INT*20) +
        (signal_watchlist_match::INT*30) + (signal_round_number::INT*5) + (signal_structuring::INT*20)
    ) AS risk_score FROM base
)
SELECT TXN_ID, ACCOUNT_ID, AMOUNT, MERCHANT, GEO_COUNTRY, GEO_CITY, CHANNEL, TXN_TIMESTAMP, DEVICE_ID,
    signal_velocity, signal_amount_anomaly, signal_geo_mismatch, signal_watchlist_match,
    signal_round_number, signal_structuring, risk_score,
    CASE WHEN risk_score >= 75 THEN 'CRITICAL' WHEN risk_score >= 50 THEN 'HIGH'
         WHEN risk_score >= 25 THEN 'MEDIUM' ELSE 'LOW' END AS risk_tier,
    CONCAT('Signals: ', IFF(signal_velocity,'VELOCITY ',''), IFF(signal_amount_anomaly,'AMOUNT_ANOMALY ',''),
        IFF(signal_geo_mismatch,'GEO_MISMATCH ',''), IFF(signal_watchlist_match,'WATCHLIST ',''),
        IFF(signal_round_number,'ROUND_NUM ',''), IFF(signal_structuring,'STRUCTURING ',''),
        '| Score: ', risk_score::VARCHAR) AS signal_explanation_admin,
    CASE WHEN risk_score >= 75 THEN 'This transaction was flagged due to multiple unusual indicators.'
         WHEN risk_score >= 50 THEN 'We noticed some unusual activity on this transaction.'
         WHEN risk_score >= 25 THEN 'Minor flag due to slight deviation from usual patterns.'
         ELSE 'Transaction appears consistent with normal activity.' END AS signal_explanation_customer
FROM scored;

-- ============================================================================
-- 7. ANALYTICS VIEWS
-- ============================================================================
CREATE OR REPLACE VIEW ANALYTICS.V_VERIFICATION_METRICS AS
WITH base AS (
    SELECT cve.RESPONSE_TYPE, cve.RESPONSE_TIME_MINUTES
    FROM AGENTS.CUSTOMER_VERIFICATION_EVENTS cve
    INNER JOIN AGENTS.FRAUD_ALERTS fa ON cve.CASE_ID = fa.CASE_ID
    WHERE cve.RESPONSE_TYPE IS NOT NULL
)
SELECT COUNT(*) AS total_verifications_sent,
    COUNT(CASE WHEN RESPONSE_TYPE='USER_CONFIRMED' THEN 1 END) AS confirmed_count,
    COUNT(CASE WHEN RESPONSE_TYPE='USER_REQUESTED_REVIEW' THEN 1 END) AS review_count,
    COUNT(CASE WHEN RESPONSE_TYPE='USER_REJECTED' THEN 1 END) AS rejected_count,
    COUNT(CASE WHEN RESPONSE_TYPE='VERIFICATION_TIMEOUT' THEN 1 END) AS timeout_count,
    ROUND(confirmed_count*100.0/NULLIF(total_verifications_sent,0),2) AS acceptance_rate_pct,
    ROUND(review_count*100.0/NULLIF(total_verifications_sent,0),2) AS hold_rate_pct,
    ROUND(rejected_count*100.0/NULLIF(total_verifications_sent,0),2) AS rejection_rate_pct,
    ROUND(timeout_count*100.0/NULLIF(total_verifications_sent,0),2) AS timeout_rate_pct,
    ROUND(AVG(CASE WHEN RESPONSE_TYPE!='VERIFICATION_TIMEOUT' THEN RESPONSE_TIME_MINUTES END),2) AS avg_response_time_minutes_excl_timeouts
FROM base;

CREATE OR REPLACE VIEW ANALYTICS.V_FRAUD_RISK_DASHBOARD AS
SELECT DATE_TRUNC('DAY', TXN_TIMESTAMP) AS metric_date,
    COUNT(*) AS total_transactions,
    COUNT(CASE WHEN RISK_SCORE > 0 THEN 1 END) AS flagged_transactions,
    ROUND(flagged_transactions*100.0/NULLIF(total_transactions,0),2) AS flag_rate_pct,
    AVG(RISK_SCORE) AS avg_risk_score,
    SUM(CASE WHEN RISK_TIER IN ('HIGH','CRITICAL') THEN AMOUNT ELSE 0 END) AS high_risk_volume
FROM CURATED.TRANSACTION_ENRICHED GROUP BY metric_date;

CREATE OR REPLACE VIEW ANALYTICS.V_AML_EXPOSURE_SUMMARY AS
SELECT t.GEO_COUNTRY AS transaction_country, a.DOMICILE_COUNTRY AS account_country,
    a.RISK_TIER AS account_risk_tier, COUNT(*) AS transaction_count,
    SUM(t.AMOUNT) AS total_exposure_amount,
    SUM(CASE WHEN t.RISK_TIER IN ('HIGH','CRITICAL') THEN t.AMOUNT ELSE 0 END) AS high_risk_exposure,
    COUNT(CASE WHEN t.SIGNAL_WATCHLIST_MATCH THEN 1 END) AS watchlist_hits,
    COUNT(DISTINCT t.ACCOUNT_ID) AS unique_accounts_exposed,
    ROUND(high_risk_exposure*100.0/NULLIF(total_exposure_amount,0),2) AS high_risk_pct_of_volume
FROM CURATED.TRANSACTION_ENRICHED t
LEFT JOIN RAW.RAW_ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
GROUP BY t.GEO_COUNTRY, a.DOMICILE_COUNTRY, a.RISK_TIER;

CREATE OR REPLACE VIEW ANALYTICS.V_KYC_COMPLIANCE_STATUS AS
SELECT KYC_STATUS, RISK_TIER, ACCOUNT_TYPE, DOMICILE_COUNTRY,
    COUNT(*) AS account_count,
    ROUND(COUNT(*)*100.0/SUM(COUNT(*)) OVER(),2) AS pct_of_total,
    ROUND(COUNT(CASE WHEN KYC_STATUS='VERIFIED' THEN 1 END) OVER()*100.0/NULLIF(COUNT(*) OVER(),0),2) AS overall_compliance_rate_pct
FROM RAW.RAW_ACCOUNTS GROUP BY KYC_STATUS, RISK_TIER, ACCOUNT_TYPE, DOMICILE_COUNTRY;

CREATE OR REPLACE VIEW ANALYTICS.V_CASE_RESOLUTION_METRICS AS
SELECT CASE_STATUS, RISK_TIER, ALERT_TYPE, ASSIGNED_ANALYST,
    COUNT(DISTINCT fa.CASE_ID) AS total_cases,
    AVG(cve.RESPONSE_TIME_MINUTES) AS avg_response_time_minutes
FROM AGENTS.FRAUD_ALERTS fa
LEFT JOIN AGENTS.CUSTOMER_VERIFICATION_EVENTS cve ON fa.CASE_ID = cve.CASE_ID
GROUP BY CASE_STATUS, RISK_TIER, ALERT_TYPE, ASSIGNED_ANALYST;

-- ============================================================================
-- 8. EMAIL NOTIFICATION INTEGRATION
-- Update ALLOWED_RECIPIENTS with your validated Snowflake email(s)
-- ============================================================================
CREATE OR REPLACE NOTIFICATION INTEGRATION FRAUDSHIELD_EMAIL_INT
  TYPE = EMAIL
  ENABLED = TRUE
  ALLOWED_RECIPIENTS = ('owendrilasaha09@gmail.com');

GRANT USAGE ON INTEGRATION FRAUDSHIELD_EMAIL_INT TO ROLE SYSADMIN;
GRANT USAGE ON INTEGRATION FRAUDSHIELD_EMAIL_INT TO ROLE COCO_AUTOMATION_ROLE;

-- ============================================================================
-- 9. TABLE GRANTS
-- ============================================================================
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA AGENTS TO ROLE COMPLIANCE_OFFICER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AGENTS TO ROLE FRAUD_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AGENTS TO ROLE AUDIT_ROLE;

-- ============================================================================
-- 10. SEED DATA — State Machine & Config
-- ============================================================================
USE SCHEMA AGENTS;

INSERT INTO CASE_STATUS_TRANSITIONS (FROM_STATUS, TO_STATUS, LABEL, REQUIRED_ROLE, REQUIRES_FOUR_EYES) VALUES
('OPEN', 'UNDER_REVIEW', 'Start Review', 'FRAUD_ANALYST_ROLE', FALSE),
('OPEN', 'RESOLVED_APPROVED', 'Approve & Release', 'FRAUD_ANALYST_ROLE', FALSE),
('OPEN', 'ESCALATED', 'Escalate', 'FRAUD_ANALYST_ROLE', FALSE),
('UNDER_REVIEW', 'RESOLVED_APPROVED', 'Approve & Release', 'FRAUD_ANALYST_ROLE', FALSE),
('UNDER_REVIEW', 'ESCALATED', 'Escalate', 'FRAUD_ANALYST_ROLE', FALSE),
('ESCALATED', 'UNDER_REVIEW', 'Return to Analyst', 'COMPLIANCE_OFFICER_ROLE', FALSE),
('ESCALATED', 'RESOLVED_APPROVED', 'Approve & Release', 'COMPLIANCE_OFFICER_ROLE', TRUE),
('ESCALATED', 'PENDING_SAR', 'Block & File SAR', 'COMPLIANCE_OFFICER_ROLE', TRUE),
('PENDING_SAR', 'SAR_FILED', 'File SAR', 'COMPLIANCE_OFFICER_ROLE', TRUE),
('PENDING_SAR', 'CLOSED', 'Close Case', 'COMPLIANCE_OFFICER_ROLE', FALSE),
('RESOLVED_APPROVED', 'CLOSED', 'Close Case', 'COMPLIANCE_OFFICER_ROLE', FALSE);

INSERT INTO APP_CONFIG (CONFIG_KEY, CONFIG_VALUE) VALUES
('ANALYST_MAX_RISK_SCORE', '60'),
('ANALYST_BLOCKED_TIERS', 'CRITICAL,HIGH');

-- Admin user mapping (change CURRENT_USER() if deploying under a different account)
INSERT INTO USER_ROLE_MAPPING (USER_NAME, ASSIGNED_ROLE, ASSIGNED_BY, STATUS)
VALUES (CURRENT_USER(), 'FRAUDSHIELD_ACCESS_ADMIN_ROLE', 'SYSTEM_ADMIN', 'ACTIVE');

-- ============================================================================
-- 11. SKILL STAGE
-- ============================================================================
CREATE STAGE IF NOT EXISTS AGENTS.SKILL_STAGE DIRECTORY = (ENABLE = TRUE);

-- After running this script, upload skills and apps using the deploy.sh/deploy.ps1 script.
